# Generated by Django 5.1.2 on 2024-11-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grupos',
            fields=[
                ('idGrupo', models.AutoField(primary_key=True, serialize=False)),
                ('cveGrupo', models.CharField(max_length=10, unique=True)),
                ('nombreGrupo', models.CharField(max_length=20)),
                ('cuatrimestreGrupo', models.CharField(max_length=30)),
                ('aulaNombre', models.CharField(max_length=30)),
                ('aulaUbicacion', models.CharField(max_length=100)),
                ('bActivo', models.BooleanField(null=True)),
            ],
        ),
    ]
