# Generated by Django 5.1.2 on 2024-11-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('idBeca', models.AutoField(primary_key=True, serialize=False)),
                ('nombreBeca', models.CharField(max_length=255)),
                ('tipoBeca', models.CharField(max_length=20)),
                ('bActivo', models.BooleanField(null=True)),
            ],
        ),
    ]
