# Generated by Django 5.1.2 on 2024-11-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('idDocente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDocente', models.CharField(max_length=255)),
                ('numeroTrabajador', models.CharField(max_length=20, unique=True)),
                ('bActivo', models.BooleanField(null=True)),
            ],
        ),
    ]
